### ISSUE TITLE
订阅没法用，获取不到节点

### ISSUE THREAD

**Issue by godzeo** [zu1k/proxypool#13]
Clash proxy-provider(Shadowrocket添加订阅方式可用)
MAC 版的小飞机，订阅没法用，获取不到节点
![image](https://user-images.githubusercontent.com/64398024/92318690-d4633280-f042-11ea-9c6c-4541fb506288.png)

**Comment by zu1k** [comment]
使用方法错误啊，这个是proxy provider的链接，肯定不能这样用的

访问 proxy.tgbot.co 后可以直接点一键导入啊，这样导入的是配置文件

**Comment by zu1k** [comment]
你用的是ss啊，ss我只测试了安卓版客户端(google play store下载的)，可以使用 https://proxy.tgbot.co/ss/sub 这个订阅链接

**Comment by zu1k** [comment]
我没有任何苹果设备，以后苹果相关的尽量不要提了，没法测试没法解决
