### ISSUE TITLE
无法导入节点

### ISSUE THREAD

**Issue by kedyao** [zu1k/proxypool#5]
![image](https://user-images.githubusercontent.com/47054558/90210952-fa216100-de21-11ea-9bb5-48bae8613504.png)

![image](https://user-images.githubusercontent.com/47054558/90210931-e5dd6400-de21-11ea-901e-248ecf1e0fa8.png)

**Comment by zu1k** [comment]
需要使用最新版的cfw，目前的版本应该是0.11.3

kedyao <notifications@github.com> 于 2020年8月14日周五 11:33写道：

**Comment by zu1k** [comment]
好像又更新了，是0.11.4
