### ISSUE TITLE
建议增加按地理位置分类节点的功能

### ISSUE THREAD

**Issue by ClarkeCheng** [zu1k/proxypool#8]
首先非常感谢作者能做出这么好的软件。我在使用的过程中发现，那么多节点混在一起，我想在里面找一个香港的节点或者美国的节点要一个一个地试才知道。能否让程序在收集到节点时，通过该节点去访问某个查询IP地址的网站，进而知道该节点服务器所在的地理位置，然后分类呢？

**Comment by zu1k** [comment]
分类是不会直接提供按国家分好类的，但是可以在节点名字后面增添一个国家名字简称

**Comment by zu1k** [comment]
加好国家信息了
